services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: PokemonInHomeDbAPI
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge